#pragma once
#include <util/IO.h>
#include <stdint.h>

#define VENDOR_ID 0x00
#define DEVICE_ID 0x02
#define COMMAND 0x04
#define STATUS 0x06
#define REVISION_ID 0x08
#define PROG_IF 0x09
#define SUBCLASS 0x0a
#define CLASS_CODE 0x0b
#define CACHE_LINE_SIZE 0x0c
#define LATENCY_TIMER 0x0d
#define HEADER_TYPE 0x0e
#define BIST 0x0f

#define HEADER_0_BAR0 0x10
#define HEADER_0_BAR1 0x14
#define HEADER_0_BAR2 0x18
#define HEADER_0_BAR3 0x1c
#define HEADER_0_BAR4 0x20
#define HEADER_0_BAR5 0x24
#define HEADER_0_CARDBUS_CIS_POINTER 0x28
#define HEADER_0_SUBSYSTEM_VENDOR_ID 0x2c
#define HEADER_0_SUBSYSTEM_ID 0x2e
#define HEADER_0_EXPANSION_ROM_BASE_ADDRESS 0x30
#define HEADER_0_CAPABILITIES_POINTER 0x34
#define HEADER_0_RESERVED0 0x35
#define HEADER_0_RESERVED1 0x38
#define HEADER_0_INTERRUPT_LINE 0x3c
#define HEADER_0_INTERRUPT_PIN 0x3d
#define HEADER_0_MIN_GRANT 0x3e
#define HEADER_0_MAX_LATENCY 0x3f

#define HEADER_1_BAR0 0x10
#define HEADER_1_BAR1 0x14
#define HEADER_1_PRIMARY_BUS_NUMBER 0x18
#define HEADER_1_SECONDARY_BUS_NUMBER 0x19
#define HEADER_1_SUBORDINATE_BUS_NUMBER 0x1a
#define HEADER_1_SECONDARY_LATENCY_TIMER 0x1b
#define HEADER_1_IO_BASE 0x1c
#define HEADER_1_IO_LIMIT 0x1d
#define HEADER_1_SECONDARY_STATUS 0x1e
#define HEADER_1_MEMORY_BASE 0x20
#define HEADER_1_MEMORY_LIMIT 0x22
#define HEADER_1_PREFETCHABLE_MEMORY_BASE 0x24
#define HEADER_1_PREFETCHABLE_MEMORY_LIMIT 0x26
#define HEADER_1_PREFETCHABLE_BASE_UPPER_32_BITS 0x28
#define HEADER_1_PREFETCHABLE_LIMIT_UPPER_32_BITE 0x2c
#define HEADER_1_IO_BASE_UPPER_16_BITS 0x30
#define HEADER_1_IO_LIMIT_UPPER_16_BITS 0x32
#define HEADER_1_CAPABILITY_POINTER 0x34
#define HEADER_1_RESERVED 0x35
#define HEADER_1_EXPANSION_ROM_BASE_ADDRESS 0x38
#define HEADER_1_INTERRUPT_LINE 0x3c
#define HEADER_1_INTERRUPT_PIN 0x3d
#define HEADER_1_BRIDGE_CONTROL 0x3e

uint32_t pciConfigReadDouble (uint8_t bus, uint8_t slot, uint8_t func, uint8_t offset);
uint16_t pciConfigReadWord (uint8_t bus, uint8_t slot, uint8_t func, uint8_t offset);
uint16_t pciCheckVendor(uint8_t bus, uint8_t slot);
//void enumerate_devices();
